# Import

In [ ]:
# Importing the libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
# Importing the dataset
car_df = pd.read_csv('cars.csv',header=None)

In [ ]:
car_df.head()

In [ ]:
car_df.columns = ['buying','maint','doors','persons','llug_boot','safity','classes']

In [ ]:
car_df.head()

# Preprocessing

In [ ]:
df = car_df.copy()

In [ ]:
df['classes'].value_counts().plot.bar()

## Missing Values

In [ ]:
df.isnull().sum()

## Encoding

In [ ]:
colname = df.columns
from sklearn import preprocessing
le = {}
for x in colname:
    le[x] = preprocessing.LabelEncoder()
for x in colname:
    df[x] = le[x].fit_transform(df[x])

In [ ]:
df.head()

## Dependent and Independent variable

In [ ]:
X = df.copy()
y = X.pop('classes')

## Scaling

In [ ]:
# from sklearn.preprocessing import StandardScaler
# scaler = StandardScaler()
# X = scaler.fit_transform(X)

## Training and Test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_val,y_train,y_val = train_test_split(X,y,test_size=.3,random_state=1)
X_train.shape,X_val.shape,y_train.shape,y_val.shape

# Decision Tree

In [ ]:
from sklearn.tree import DecisionTreeClassifier
m = DecisionTreeClassifier(random_state=1,min_samples_leaf=2)
m.fit(X_train,y_train)

In [ ]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
y_pred = m.predict(X_val)
cm = confusion_matrix(y_val,y_pred)
print(cm)
print(classification_report(y_val,y_pred))
print(accuracy_score(y_val,y_pred))

In [ ]:
m.feature_importances_

In [ ]:
# Drawing the tree
from sklearn import tree
with open('m','w') as f:
    f = tree.export_graphviz(m,feature_names=X_train.columns,out_file=f)

## SVC

In [ ]:
from sklearn.svm import SVC
m = SVC(C=70)
m.fit(X_train,y_train)

In [ ]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
y_pred = m.predict(X_val)
cm = confusion_matrix(y_val,y_pred)
print(cm)
print(classification_report(y_val,y_pred))
print(accuracy_score(y_val,y_pred))

## Logistic Regression

In [ ]:
from sklearn.linear_model import LogisticRegression
m = LogisticRegression()
m.fit(X_train,y_train)

In [ ]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
y_pred = m.predict(X_val)
cm = confusion_matrix(y_val,y_pred)
print(cm)
print(classification_report(y_val,y_pred))
print(accuracy_score(y_val,y_pred))

## Extra Trees Classifier

In [24]:
from sklearn.ensemble import ExtraTreesClassifier
m = ExtraTreesClassifier(200)
m.fit(X_train,y_train)

ExtraTreesClassifier(bootstrap=False, class_weight=None, criterion='gini',
           max_depth=None, max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=200, n_jobs=1,
           oob_score=False, random_state=None, verbose=0, warm_start=False)

In [25]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
y_pred = m.predict(X_val)
cm = confusion_matrix(y_val,y_pred)
print(cm)
print(classification_report(y_val,y_pred))
print(accuracy_score(y_val,y_pred))

[[107   0   4   0]
 [  7  15   0   0]
 [  6   0 362   0]
 [  1   0   0  17]]
             precision    recall  f1-score   support

          0       0.88      0.96      0.92       111
          1       1.00      0.68      0.81        22
          2       0.99      0.98      0.99       368
          3       1.00      0.94      0.97        18

avg / total       0.97      0.97      0.96       519

0.9653179190751445


## Random Forest 

In [30]:
from sklearn.ensemble import RandomForestClassifier
m = RandomForestClassifier(max_features=.5,n_estimators=100)
m.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features=0.5, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [31]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
y_pred = m.predict(X_val)
cm = confusion_matrix(y_val,y_pred)
print(cm)
print(classification_report(y_val,y_pred))
print(accuracy_score(y_val,y_pred))

[[105   1   4   1]
 [  2  20   0   0]
 [ 10   0 358   0]
 [  0   0   0  18]]
             precision    recall  f1-score   support

          0       0.90      0.95      0.92       111
          1       0.95      0.91      0.93        22
          2       0.99      0.97      0.98       368
          3       0.95      1.00      0.97        18

avg / total       0.97      0.97      0.97       519

0.9653179190751445
